services:
  - type: web
    name: ilus-school-of-thoughts
    env: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
